name: Run Robot Tests and Publish Allure Report

on: [push, pull_request]

jobs:
  test:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout repository
      uses: actions/checkout@v3

    - name: Setup Python
      uses: actions/setup-python@v4
      with:
        python-version: "3.10"

    - name: Install dependencies
      run: |
        pip install -r requirements.txt
        npm install -g allure-commandline
    - name: Run Robot Framework Tests with Allure Listener
      run: |
        robot --listener "allure_robotframework;ALLURE_RESULTS_DIR=allure-result" --test "*CREDT-172*" tests/features
    - name: Debug - Show Allure result files
      run: |
        echo "📂 Conteúdo da pasta allure-result:"
        ls -l allure-result || echo "⚠️ Pasta não encontrada ou vazia."
    - name: Generate Allure Report with customizations
      run: |
        project_root="$(pwd)"
        output_folder="${project_root}/allure-report"
        results_folder="${project_root}/allure-result"
        custom_styles_path="${project_root}/allure-custom/styles.css"
        logo_source_path="${project_root}/allure-custom/neuro-logo.svg"
        favicon_source_path="${project_root}/allure-custom/favicon.ico"
        logo_target_folder="$output_folder/plugin/custom-logo"
        favicon_target_path="$output_folder/favicon.ico"
        allure generate "$results_folder" --clean --lang br -o "$output_folder"
        if [ ! -f "$output_folder/index.html" ]; then
          echo "❌ Erro ao gerar o relatório Allure."
          exit 1
        fi
        cp "$custom_styles_path" "$output_folder/custom.css"
        sed -i '/styles.css/a <link rel="stylesheet" type="text/css" href="custom.css">' "$output_folder/index.html"
        sed -i 's|<title>Allure Report</title>|<title>Neuro Report</title>|' "$output_folder/index.html"
        summary_file="$output_folder/widgets/summary.json"
        if [ -f "$summary_file" ]; then
          sed -i 's/Allure Report/Neuro Report/g' "$summary_file"
        fi
        mkdir -p "$logo_target_folder"
        cp "$logo_source_path" "$logo_target_folder/neuro-logo.svg"
        cp "$favicon_source_path" "$favicon_target_path"
        if grep -q '<link rel="icon"' "$output_folder/index.html"; then
          sed -i 's|<link rel="icon[^>]*>|<link rel="icon" type="image/x-icon" href="favicon.ico">|' "$output_folder/index.html"
        else
          sed -i '/<head>/a <link rel="icon" type="image/x-icon" href="favicon.ico">' "$output_folder/index.html"
        fi
    - name: Deploy Allure Report to GitHub Pages
      uses: peaceiris/actions-gh-pages@v3
      with:
        github_token: ${{ secrets.GITHUB_TOKEN }}
        publish_dir: allure-report
        publish_branch: gh-pages